services:
  # Servicio para el Backend (Node.js)
  - type: web
    name: api-noticias-flat
    runtime: node
    rootDir: noticias_api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        sync: false 
      - key: PORT
        value: 3000

# seccion correcta para React
staticSites:
  - name: frontend-noticias-flat
    rootDir: frontend-noticias
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: api-noticias-flat
          property: host