services:
  # 1. Servicio para el Backend (Node.js)
  - type: web
    name: api-noticias-flat
    env: node 
    rootDir: noticias_api
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: ADMIN_PASSWORD
        sync: false 
      - key: PORT
        value: 3000

  # 2. Servicio para el Frontend (React)
  - type: web 
    name: frontend-noticias-flat
    env: static 
    rootDir: frontend-noticias
    buildCommand: npm install && npm run build
    staticPublishDir: dist 
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: api-noticias-flat
          property: url 